Added SGI-Content features
o3de/community pull request #117
Opened 2022-03-10 00:00 UTC by lsemp3d

Signed-off-by: lsemp3d <58790905+lsemp3d@users.noreply.github.com>

2022-03-11 16:47 UTC, mcphedar requested changes
Hey Luis. We don't want to remove the terrain and vegetation systems. Can you add those back in ?

2022-03-15 17:26 UTC, hultonha commented on features/sigjson/sig-content-features.json
> +      }
I've listed White Box as it's own subsystem with various features so we might want to remove this from here?

2022-03-15 17:27 UTC, hultonha commented on features/sigjson/sig-content-features.json
> +            "Platform": "",
It looks like the original values for this have been wiped, I'd suggested keeping the original changes

2022-03-15 17:28 UTC, hultonha commented on features/sigjson/sig-content-features.json
> +            "Platform": "",
Same as above

2022-03-15 17:38 UTC, monroegm approved these changes

2022-03-15 17:42 UTC, merged